<testsuites>
	<testsuite name="Customized UndoRedoStack ByDelegation" tests="14">
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::DoIt">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:128 DoIt: expected == result expected:	3	but was:	0	">
DoIt: expected == result expected:	3	but was:	0	
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::DoItWithException">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:174 &quot;Command throws but SUT not!&quot;">
&quot;Command throws but SUT not!&quot;
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::DoItExceptionNeutral">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:243 &quot;Command throws but SUT not!&quot;">
&quot;Command throws but SUT not!&quot;
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::Undo">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:145 Undo: true == urMngr.isRedoable() expected:	1	but was:	0	">
Undo: true == urMngr.isRedoable() expected:	1	but was:	0	
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::UndoWithException">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:191 UndoWithException: expected == result expected:	3	but was:	0	">
UndoWithException: expected == result expected:	3	but was:	0	
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::UndoExceptionNeutral">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:255 &quot;Command throws but SUT not!&quot;">
&quot;Command throws but SUT not!&quot;
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::Redo">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:159 Redo: expected == result expected:	3	but was:	0	">
Redo: expected == result expected:	3	but was:	0	
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::RedoWithException">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:220 &quot;Command throws but SUT not!&quot;">
&quot;Command throws but SUT not!&quot;
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::RedoExceptionNeutral">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:267 &quot;Command throws but SUT not!&quot;">
&quot;Command throws but SUT not!&quot;
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::IsUndoable">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:96 IsUndoable: true == urMngr.isUndoable() expected:	1	but was:	0	">
IsUndoable: true == urMngr.isUndoable() expected:	1	but was:	0	
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::IsRedoable">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:105 IsRedoable: true == urMngr.isRedoable() expected:	1	but was:	0	">
IsRedoable: true == urMngr.isRedoable() expected:	1	but was:	0	
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::IsNotRedoableAfterDoIt"/>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::UndoStackSize">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:76 UndoStackSize: 1 == urMngr.undoStackSize() expected:	1	but was:	0	">
UndoStackSize: 1 == urMngr.undoStackSize() expected:	1	but was:	0	
			</failure>
		</testcase>
		<testcase classname="Customized UndoRedoStack ByDelegation" name="CustomizedUndoRedoStackByDelegationTest::RedoStackSize">
			<failure message="C:\Users\Gerd\git\CppNeon\Cpp-UndoRedoFramework\Test\UndoRedoTestCute\include/UndoRedoTest/UndoRedoStackTest.h:87 RedoStackSize: 1 == urMngr.redoStackSize() expected:	1	but was:	0	">
RedoStackSize: 1 == urMngr.redoStackSize() expected:	1	but was:	0	
			</failure>
		</testcase>
	</testsuite>
</testsuites>
